# Generated by Django 3.2.12 on 2023-03-15 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
