# Generated by Django 3.2.12 on 2023-03-16 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20230316_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active_tariff',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='end_at',
        ),
        migrations.AddField(
            model_name='tariff',
            name='ends_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 13, 0, 24, 100101), verbose_name='Заканчивается'),
        ),
    ]
