# Generated by Django 3.2.12 on 2023-03-16 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20230316_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='ends_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 13, 1, 42, 206111), verbose_name='Заканчивается'),
        ),
    ]
