# Generated by Django 3.2.12 on 2023-03-16 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_alter_tariff_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='name',
            field=models.CharField(choices=[('classic', 'Классическое'), ('low_carb', 'Низкоуглеводное'), ('vegeterian', 'Вегетарианское'), ('keto', 'Кето')], default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tariff',
            name='ends_at',
            field=models.DateField(default=datetime.datetime(2023, 4, 16, 13, 16, 12, 526090), verbose_name='Заканчивается'),
        ),
    ]
