# Generated by Django 3.2.12 on 2023-03-16 12:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_alter_tariff_ends_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='ends_at',
            field=models.DateField(default=datetime.datetime(2023, 4, 16, 15, 4, 7, 633934), verbose_name='Заканчивается'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
