# Generated by Django 3.2.12 on 2023-03-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_auto_20230316_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(blank=True, null=True, verbose_name='Тариф заканчивается'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='bee_allergy',
            field=models.BooleanField(verbose_name='Продукты пчеловодства '),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='fish_allergy',
            field=models.BooleanField(verbose_name='Рыба и морепродукты'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='lactose_allergy',
            field=models.BooleanField(verbose_name='Молочные продукты '),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='seed_allergy',
            field=models.BooleanField(verbose_name='Зерновые'),
        ),
    ]
