# Generated by Django 3.2.12 on 2023-03-16 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0013_auto_20230316_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 15, 19, 21, 31, 369732), verbose_name='Тариф заканчивается'),
        ),
    ]
