# Generated by Django 4.1.7 on 2023-03-17 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0015_remove_tariff_breakfast_remove_tariff_desert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='number_of_meals',
        ),
        migrations.AddField(
            model_name='tariff',
            name='breakfast',
            field=models.BooleanField(default=1, verbose_name='Включены завтраки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='desert',
            field=models.BooleanField(default=1, verbose_name='Включены десерты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='dinner',
            field=models.BooleanField(default=1, verbose_name='Включены ужины'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='lunch',
            field=models.BooleanField(default=1, verbose_name='Включены обеды'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 14, 16, 59, 36780), verbose_name='Тариф заканчивается'),
        ),
    ]
