# Generated by Django 4.1.7 on 2023-03-17 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0016_remove_tariff_number_of_meals_tariff_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 15, 21, 55, 820616), verbose_name='Тариф заканчивается'),
        ),
    ]
