# Generated by Django 4.1.7 on 2023-03-17 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0017_alter_customuser_tariff_ends_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 15, 28, 59, 77434), verbose_name='Тариф заканчивается'),
        ),
    ]
