# Generated by Django 3.2.12 on 2023-03-18 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0018_alter_customuser_tariff_ends_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=255, unique=True, verbose_name='Промокод')),
                ('lasts_till', models.DateField(verbose_name='Действителен до')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 12, 11, 49, 381652), verbose_name='Тариф заканчивается'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='bee_allergy',
            field=models.BooleanField(verbose_name='Продукты пчеловодства'),
        ),
    ]
