# Generated by Django 4.1.7 on 2023-03-18 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0018_alter_customuser_tariff_ends_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='Аллергия')),
            ],
            options={
                'verbose_name': 'Аллергия',
                'verbose_name_plural': 'Аллергии',
            },
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='bee_allergy',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='fish_allergy',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='lactose_allergy',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='meat_allergy',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='nut_allergy',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='seed_allergy',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 14, 40, 40, 940863), verbose_name='Тариф заканчивается'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='allergens',
            field=models.ManyToManyField(blank=True, null=True, related_name='tariffs', to='authorization.allergen'),
        ),
    ]
