# Generated by Django 4.1.7 on 2023-03-18 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0019_allergen_remove_tariff_bee_allergy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 14, 41, 32, 354082), verbose_name='Тариф заканчивается'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='tariffs', to='authorization.allergen'),
        ),
    ]
