# Generated by Django 3.2.12 on 2023-03-19 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0019_auto_20230318_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='name',
            field=models.CharField(choices=[('fish_allergy', 'Рыба и морепродукты'), ('meat_allergy', 'Мясо'), ('seed_allergy', 'Зерновые'), ('bee_allergy', 'Продукты пчеловодства'), ('nut_allergy', 'Орехи и бобовые'), ('lactose_allergy', 'Молочные продукты')], max_length=15, verbose_name='Аллергия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 18, 15, 15, 36, 157450), verbose_name='Тариф заканчивается'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость'),
        ),
    ]
