# Generated by Django 3.2.12 on 2023-03-20 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0020_auto_20230319_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 19, 16, 39, 19, 382488), verbose_name='Тариф заканчивается'),
        ),
    ]
