# Generated by Django 3.2.12 on 2023-03-18 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0020_auto_20230318_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 12, 40, 12, 991433), verbose_name='Тариф заканчивается'),
        ),
    ]
