# Generated by Django 4.1.7 on 2023-03-18 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0020_alter_customuser_tariff_ends_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 15, 9, 3, 780731), verbose_name='Тариф заканчивается'),
        ),
    ]
