# Generated by Django 4.1.7 on 2023-03-18 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0021_alter_customuser_tariff_ends_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 15, 10, 38, 697119), verbose_name='Тариф заканчивается'),
        ),
    ]
