# Generated by Django 3.2.12 on 2023-03-18 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0021_alter_customuser_tariff_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Использован ли'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 13, 12, 13, 407029), verbose_name='Тариф заканчивается'),
        ),
    ]
