# Generated by Django 3.2.12 on 2023-03-20 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0021_alter_customuser_tariff_ends_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 19, 16, 40, 47, 460061), verbose_name='Тариф заканчивается'),
        ),
    ]
