# Generated by Django 3.2.12 on 2023-03-18 10:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0022_auto_20230318_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.promocode', verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 13, 13, 50, 657516), verbose_name='Тариф заканчивается'),
        ),
    ]
