# Generated by Django 3.2.12 on 2023-03-18 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0023_auto_20230318_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tariff_ends_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 13, 17, 50, 736569), verbose_name='Тариф заканчивается'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(blank=True, choices=[('classic', 'Классическое'), ('low_carb', 'Низкоуглеводное'), ('vegeterian', 'Вегетарианское'), ('keto', 'Кето')], max_length=255, verbose_name='Название'),
        ),
    ]
