# Generated by Django 3.2.12 on 2023-03-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipeingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('PS', 'шт.'), ('GR', 'гр.'), ('ML', 'мл'), ('TT', 'по вкусу')], max_length=2, verbose_name='Единица измерения'),
        ),
    ]
