# Generated by Django 3.2.12 on 2023-03-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0019_auto_20230318_1910'),
        ('recipes', '0007_auto_20230316_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='authorization.Allergen'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_time',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('desert', 'Десерт')], default='lunch', max_length=9, verbose_name='Временной промежуток'),
        ),
    ]
