# Generated by Django 4.1.7 on 2023-03-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230316_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_time',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('desert', 'Десерт')], default='lunch', max_length=9, verbose_name='Временной промежуток'),
        ),
    ]
