# Generated by Django 4.1.7 on 2023-03-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0019_allergen_remove_tariff_bee_allergy_and_more'),
        ('recipes', '0008_recipe_meal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergens',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipes', to='authorization.allergen'),
        ),
    ]
