# Generated by Django 3.2.12 on 2023-03-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230318_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ad',
            field=models.BooleanField(default=False, verbose_name='Рекламный рецепт'),
        ),
    ]
